//Peliculas 2024 con puntuacion mayor a 8.5
const peliculas_mejor_rating = [
        {'anime': 'Gintama: The Very Final', 'score': 9.04}, 
        {'anime': 'A Silent Voice', 'score': 8.93}, 
        {'anime': 'Gintama: The Movie: The Final Chapter: Be Forever Yorozuya', 'score': 8.9}, 
        {'anime': 'Violet Evergarden: The Movie', 'score': 8.87}, 
        {'anime': 'Your Name.', 'score': 8.84}, 
        {'anime': 'Kaguya-sama: Love is War - The First Kiss That Never Ends', 'score': 8.78}, 
        {'anime': 'Kizumonogatari Part 3: Cold-Blooded', 'score': 8.78}, 
        {'anime': 'Spirited Away', 'score': 8.77}, 
        {'anime': "Fate/stay night: Heaven's Feel - III. Spring Song", 'score': 8.66}, 
        {'anime': "Howl's Moving Castle", 'score': 8.66}, 
        {'anime': 'Princess Mononoke', 'score': 8.66}, 
        {'anime': 'Made in Abyss: Dawn of the Deep Soul', 'score': 8.61}, 
        {'anime': 'The Disappearance of Haruhi Suzumiya', 'score': 8.6}, 
        {'anime': 'Demon Slayer: Kimetsu no Yaiba - The Movie: Mugen Train', 'score': 8.59}, 
        {'anime': 'Rascal Does Not Dream of a Dreaming Girl', 'score': 8.59}, 
        {'anime': 'Evangelion: 3.0+1.0 Thrice Upon a Time', 'score': 8.59}, 
        {'anime': 'Gurren Lagann The Movie: The Lights in the Sky are Stars', 'score': 8.58}, 
        {'anime': 'Kizumonogatari Part 2: Hot-Blooded', 'score': 8.57}, 
        {'anime': 'Wolf Children', 'score': 8.57}, 
        {'anime': 'I Want To Eat Your Pancreas', 'score': 8.55}, 
        {'anime': 'Perfect Blue', 'score': 8.55}, 
        {'anime': 'Neon Genesis Evangelion: The End of Evangelion', 'score': 8.55}, 
        {'anime': 'Revue Starlight: The Movie', 'score': 8.55}, 
        {'anime': 'The Garden of Sinners Chapter 5: Paradox Spiral', 'score': 8.52}, 
        {'anime': 'Gintama: The Movie', 'score': 8.52}, 
        {'anime': 'Grave of the Fireflies', 'score': 8.52}
    ]